feat: Added Image and Input Component
xii-vi/RA-0ne pull request #4
Opened 2022-02-05 06:16 UTC by xii-vi

# Image

 - ### Responsive Image
 - ### Round Image
 - ### Square Imag
![Screenshot (23)](https://user-images.githubusercontent.com/86154835/152630980-66c80216-ff17-42d9-93e7-f6fe4c9bed40.png)

# Input

 - ### Standard Input
 - ### Validation and Error Inputs

![Screenshot (25)](https://user-images.githubusercontent.com/86154835/152630982-2f528da6-cb11-4b7b-8841-4a68ac007a23.png)

2022-02-05 06:21 UTC, sanjay-xdr approved these changes
everthing looks good

2022-02-05 06:21 UTC, sanjay-xdr commented on pages/image.html
> +                <img>
you need this tag or its by mistake?

2022-02-05 06:26 UTC, xii-vi commented on pages/image.html
> +                <img>
it is needed as I am planning to complete the navigation after the P0 Screens.

2022-02-05 06:28 UTC, syed-shaida-hussain requested changes
Do these minor changes . Rest is good.

2022-02-05 06:28 UTC, syed-shaida-hussain commented on pages/input.html
> +                <img>
What is this img tag here?

2022-02-05 06:28 UTC, syed-shaida-hussain commented on stylesheet/input.css
> +}
try to name --warning-icon as --warning-icon-color or something like that because it is a color not an icon.

2022-02-05 06:38 UTC, xii-vi commented on stylesheet/input.css
> +}
_Suggested changes are made_

2022-02-05 06:49 UTC, amirnathani9 commented on pages/input.html
> +            <div class="right-side-container">
use proper naming convention

2022-02-05 06:54 UTC, amirnathani9 reviewed
Do the suggested changes. Everything looks good

2022-02-05 07:42 UTC, xii-vi commented on pages/input.html
> +            <div class="right-side-container">
Suggested changes are made

2022-02-05 07:45 UTC, merged

2022-02-20 15:42 UTC, amirnathani9 reviewed
Looks Good